return {
  "---NORMAL---",
  "",
   "--- File Operations ---",
  "<leader>w - Save the current file",
  "<leader>q - Quit Neovim",
  "",
  "--- Splits ---",
  "<C-A-v> - Open a vertical split",
  "<C-A-h> - Open a horizontal split",
  "<C-h> - Move to the left split",
  "<C-j> - Move to the below split",
  "<C-k> - Move to the above split",
  "<C-l> - Move to the right split",
  "<A-h> - Resize split left",
  "<A-j> - Resize split up",
  "<A-k> - Resize split down",
  "<A-l> - Resize split right",
  "",
  "--- Buffers ---",
  "<A-[> - Cycle to the previous buffer",
  "<A-]> - Cycle to the next buffer",
  "<leader>bp - Pick a buffer",
  "<leader>bc - Close a picked buffer",
  "<leader>bd - Delete the current buffer",
  "",
  "--- Telescope ---",
  "<leader>tf - Find files",
  "<leader>td - Show diagnostics",
  "<leader>tw - Search text in files (live grep)",
  "<leader>th - Search help tags",
  "",
  "--- LSP ---",
  "<leader>f - Format the current buffer",
  "<leader>h - Show hover information",
  "<F2> - Rename symbol",
  "<leader>ld - Go to definition",
  "<leader>lr - List references",
  "<leader>la - Show code actions",
  "<leader>lt - Toggle diagnostics in Trouble",
  "<leader>lf - Functions and classes list",
  "{ - Previous Function",
  "} - Next Function",
  "",
  "--- Explorer ---",
  "<leader>e - Open Neotree on the left",
  "<leader>o - Toggle Neotree",
  "<leader>fe - Open a floating Neotree window",
  "",
  "--- Debugging ---",
  "<leader>bb - Toggle breakpoint",
  "<F5> - Start/continue debugging",
  "<F6> - Step into",
  "<F7> - Step over",
  "<F8> - Terminate debugging",
  "",
  "--- Miscellaneous ---",
  "<F3> - Comment the line",
  "<leader>cp - Pick a color (color picker)",
  "<leader>nn - Toggle relative number",
  "zc - Close a fold",
  "za - Open a fold",
  "zR - Open all folds",
  "zM - Close all folds",
  "<leader>db - Toggle database UI",
  "<leader>m - Start multicursor",
  "<leader>help - This help menu",
  "P - In NeoTree open the preview window"
}
